services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "--head", "http://minio:9000/minio/health/live"]
      interval: 3s
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ../data/minio:/data
    command: server /data --console-address ":9001"

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    environment:
      BUCKET_NAME: ${BUCKET_NAME}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_KEY: ${ACCESS_KEY}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    entrypoint: |
      /bin/sh -c '
      /usr/bin/mc alias set s3service http://minio:9000 "${MINIO_ROOT_USER}" "${MINIO_ROOT_PASSWORD}";
      /usr/bin/mc mb s3service/"${BUCKET_NAME}";
      /usr/bin/mc admin user add s3service "${ACCESS_KEY}" "${SECRET_KEY}";
      /usr/bin/mc admin policy attach s3service readwrite --user "${ACCESS_KEY}";
      exit 0;
      '
