services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "--head", "http://minio:9000/minio/health/live"]
      interval: 3s
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ../data/minio:/data
    command: server /data --console-address ":9001"

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    environment:
      BUCKET_NAME: ${STORAGE_BUCKET}
      SECRET_KEY: ${STORAGE_SECRET_KEY}
      ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    entrypoint: |
      /bin/sh -c '
      /usr/bin/mc alias set s3service http://minio:9000 "${MINIO_ROOT_USER}" "${MINIO_ROOT_PASSWORD}";
      /usr/bin/mc mb s3service/"${STORAGE_BUCKET}";
      /usr/bin/mc admin user add s3service "${STORAGE_ACCESS_KEY}" "${STORAGE_SECRET_KEY}";
      /usr/bin/mc admin policy attach s3service readwrite --user "${STORAGE_ACCESS_KEY}";
      exit 0;
      '

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
